### ISSUE TITLE
Using AD Auth for Databricks SDK

### ISSUE THREAD

**Issue by ishitam8** [aminekaabachi/azure-databricks-sdk-python#24]
Can you give an example of creating the client with AAD auth?
Or point to some documentation or code snippet?
How shall i get management token and databricks AD token?
What libraries to be used etc?

**Comment by aminekaabachi** [comment]
Hello ishitam8,

You can use this:

```
from azure_databricks_sdk_python import Client, AuthMethods
Client(auth_method=AuthMethods.AZURE_AD_USER, databricks_instance="<instance>", access_token="<token>")
```

The SDK is still in active development. We should get a stable version in few weeks from now.

You can checkout my article for [Ways to authenticate Azure Databricks REST API](https://kaabachi.io/ways-to-authenticate-azure-databricks-api/) for understanding more about Databricks API auth.

Does this solve your issue?

**Comment by aminekaabachi** [comment]
Please refer to this link for more details: https://azure-databricks-sdk-python.readthedocs.io/en/latest/user/advanced.html#authenticate-using-a-service-principal
